break into ci and cd

diff --git a/helm/k8sCI/templates/tasks/github-run-command.yaml b/helm/k8sCI/templates/tasks/github-run-command.yaml
--- a/helm/k8sCI/templates/tasks/github-run-command.yaml
+++ b/helm/k8sCI/templates/tasks/github-run-command.yaml
@@ -1,7 +1,9 @@
+{{- $fullName := include "k8sCI.fullname" . -}}
+
 apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
-  name: {{ include "k8sCI.fullname" . }}-post-status-github
+  name: {{ include "k8sCI.fullname" . }}-run-command-github
   labels:
     {{- include "k8sCI.labels" . | nindent 4 }}
 spec:
@@ -15,16 +17,44 @@ spec:
     - name: git_sha
     - name: ref
     - name: image
-    - name: pr-url
+    - name: command
+    - name: htmlurl
   results:
     - name: status
     - name: description
   steps:
-    - name: post-status-github
+    - name: run
       image: "$(params.image)"
       workingDir: "/workspace/git-repo"
       env:
-
+      {{- range .Values.pipelineEnvSecrets }}
+      - name: {{ .name }}
+        valueFrom:
+          secretKeyRef:
+            name: {{ $fullName }}
+            key: {{ .name }}
+      {{- end }}
+      command:
+        - "bash"
+      args:
+        - "-cx"
+        - |
+          set +e;
+          $(params.command);
+          RESULT=$?
+          [ $RESULT -eq 0 ] && echo "success" > /tekton/home/status || echo "failure" > /tekton/home/status;
+          [ $RESULT -eq 0 ] && echo "build succeeded." > /tekton/home/description || echo "build failed." > /tekton/home/description
+          exit 0;
+      volumeMounts:
+      - mountPath: /tekton/home
+        name: home
+      - mountPath: /var/lib/docker
+        name: dind-storage
+      - mountPath: /var/run/
+        name: dind-socket
+    - name: post-status
+      image: "$(params.image)"
+      workingDir: "/workspace/git-repo"
       command:
         - "bash"
       args:
@@ -43,40 +73,35 @@ spec:
     - name: report-if-error
       image: "$(params.image)"
       workingDir: "/workspace/git-repo"
-      env:
-        - name: SLACK_WEBHOOK
-          valueFrom:
-            secretKeyRef:
-              name: {{ include "k8sCI.fullname" . }}
-              key: slack-webhook
       command:
         - "bash"
       args:
         - "-cx"
         - |
           echo "slack notifcation if error";
+          export AWS_DEFAULT_REGION=us-west-2;
+          export SLACK_WEBHOOK=$(aws ssm get-parameters --with-decryption  --names /cicd/slack_webhook | jq .Parameters[0].Value | sed -e 's/^"//' -e 's/"$//');
           export STATE=$(cat /tekton/home/status)
           export DESCRIPTION=$(cat /tekton/home/description)
-          export VERSION=$(make version || echo "unversioned")
-          [ "$STATE" != "success" ] && export color="danger" || export color="danger"
-
-          DATA="{\
-              \"attachments\": [\
-                  {\
-                      \"fallback\": \"$(params.org)/$(params.repo) - $STATEversion=${VERSION}\",
-                      \"title\": \"$(params.org)/$(params.repo) - $STATE\",
-                      \"title_link\": \"$CODEBUILD_BUILD_URL\",
-                      \"color\": \"$color\",
-                      \"text\": \"$1\n\n<$(params.pr-url)/|Open>\"
-                  }\
-              ]\
-          }"
-
-
-          curl -s -X POST -H 'Content-type: application/json' --data "$DATA" $SLACK_WEBHOOK > /dev/null
+          export VERSION=$(make version)
+          [ "$STATE" != "success" ] && slack-message "$(params.org)/$(params.repo) version=${VERSION} FAILURE: ${STATE}: ${DESCRIPTION}" danger
       volumeMounts:
       - mountPath: /tekton/home
         name: home
+  sidecars:
+  - image: docker:18.05-dind
+    name: server
+    securityContext:
+      privileged: true
+    volumeMounts:
+      - mountPath: /var/lib/docker
+        name: dind-storage
+      - mountPath: /var/run/
+        name: dind-socket
   volumes:
     - name: home
+      emptyDir: {}
+    - name: dind-storage
+      emptyDir: {}
+    - name: dind-socket
       emptyDir: {}
